platform :ios, '9.0'

target ‘Billunion’ do

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'FMDB'
pod 'SDAutoLayout'
pod 'MJExtension'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'MQTTKit'

pod 'AMapLocation'
pod 'AMapNavi'

pod 'ActionSheetPicker'


end
